// Code generated by ent, DO NOT EDIT.

package slider

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the slider type in the database.
	Label = "slider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the createby field in the database.
	FieldCreateBy = "create_by"
	// FieldImageName holds the string denoting the image_name field in the database.
	FieldImageName = "image_name"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// Table holds the table name of the slider in the database.
	Table = "sliders"
)

// Columns holds all SQL columns for slider fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldImageName,
	FieldImageURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Slider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the createBy field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByImageName orders the results by the image_name field.
func ByImageName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageName, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}
