apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecit-service-deployment
spec:
  selector:
    matchLabels:
      app: kubecit-service
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kubecit-service
    spec:
      containers:
        - name: kubecit-service
          image: chaoyue/kubecit-service:latest
          ports:
            - containerPort: 8000
