// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kubecit-service/ent/category"
	"kubecit-service/ent/course"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseCreate is the builder for creating a Course entity.
type CourseCreate struct {
	config
	mutation *CourseMutation
	hooks    []Hook
}

// SetLevel sets the "level" field.
func (cc *CourseCreate) SetLevel(i int32) *CourseCreate {
	cc.mutation.SetLevel(i)
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CourseCreate) SetUpdatedAt(t time.Time) *CourseCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetName sets the "name" field.
func (cc *CourseCreate) SetName(s string) *CourseCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetDetail sets the "detail" field.
func (cc *CourseCreate) SetDetail(s string) *CourseCreate {
	cc.mutation.SetDetail(s)
	return cc
}

// SetCover sets the "cover" field.
func (cc *CourseCreate) SetCover(s string) *CourseCreate {
	cc.mutation.SetCover(s)
	return cc
}

// SetPrice sets the "price" field.
func (cc *CourseCreate) SetPrice(f float32) *CourseCreate {
	cc.mutation.SetPrice(f)
	return cc
}

// SetTags sets the "tags" field.
func (cc *CourseCreate) SetTags(s string) *CourseCreate {
	cc.mutation.SetTags(s)
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *CourseCreate) SetCreatedAt(s string) *CourseCreate {
	cc.mutation.SetCreatedAt(s)
	return cc
}

// SetStatus sets the "status" field.
func (cc *CourseCreate) SetStatus(i int32) *CourseCreate {
	cc.mutation.SetStatus(i)
	return cc
}

// SetCategoryID sets the "category_id" field.
func (cc *CourseCreate) SetCategoryID(i int) *CourseCreate {
	cc.mutation.SetCategoryID(i)
	return cc
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (cc *CourseCreate) SetNillableCategoryID(i *int) *CourseCreate {
	if i != nil {
		cc.SetCategoryID(*i)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CourseCreate) SetID(s string) *CourseCreate {
	cc.mutation.SetID(s)
	return cc
}

// SetOwnerID sets the "owner" edge to the Category entity by ID.
func (cc *CourseCreate) SetOwnerID(id int) *CourseCreate {
	cc.mutation.SetOwnerID(id)
	return cc
}

// SetNillableOwnerID sets the "owner" edge to the Category entity by ID if the given value is not nil.
func (cc *CourseCreate) SetNillableOwnerID(id *int) *CourseCreate {
	if id != nil {
		cc = cc.SetOwnerID(*id)
	}
	return cc
}

// SetOwner sets the "owner" edge to the Category entity.
func (cc *CourseCreate) SetOwner(c *Category) *CourseCreate {
	return cc.SetOwnerID(c.ID)
}

// Mutation returns the CourseMutation object of the builder.
func (cc *CourseCreate) Mutation() *CourseMutation {
	return cc.mutation
}

// Save creates the Course in the database.
func (cc *CourseCreate) Save(ctx context.Context) (*Course, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CourseCreate) SaveX(ctx context.Context) *Course {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CourseCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CourseCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CourseCreate) check() error {
	if _, ok := cc.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Course.level"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Course.updated_at"`)}
	}
	if _, ok := cc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Course.name"`)}
	}
	if _, ok := cc.mutation.Detail(); !ok {
		return &ValidationError{Name: "detail", err: errors.New(`ent: missing required field "Course.detail"`)}
	}
	if _, ok := cc.mutation.Cover(); !ok {
		return &ValidationError{Name: "cover", err: errors.New(`ent: missing required field "Course.cover"`)}
	}
	if _, ok := cc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Course.price"`)}
	}
	if _, ok := cc.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Course.tags"`)}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Course.created_at"`)}
	}
	if _, ok := cc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Course.status"`)}
	}
	return nil
}

func (cc *CourseCreate) sqlSave(ctx context.Context) (*Course, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Course.ID type: %T", _spec.ID.Value)
		}
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CourseCreate) createSpec() (*Course, *sqlgraph.CreateSpec) {
	var (
		_node = &Course{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(course.Table, sqlgraph.NewFieldSpec(course.FieldID, field.TypeString))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Level(); ok {
		_spec.SetField(course.FieldLevel, field.TypeInt32, value)
		_node.Level = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(course.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.Name(); ok {
		_spec.SetField(course.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cc.mutation.Detail(); ok {
		_spec.SetField(course.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if value, ok := cc.mutation.Cover(); ok {
		_spec.SetField(course.FieldCover, field.TypeString, value)
		_node.Cover = value
	}
	if value, ok := cc.mutation.Price(); ok {
		_spec.SetField(course.FieldPrice, field.TypeFloat32, value)
		_node.Price = value
	}
	if value, ok := cc.mutation.Tags(); ok {
		_spec.SetField(course.FieldTags, field.TypeString, value)
		_node.Tags = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(course.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.Status(); ok {
		_spec.SetField(course.FieldStatus, field.TypeInt32, value)
		_node.Status = value
	}
	if nodes := cc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   course.OwnerTable,
			Columns: []string{course.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseCreateBulk is the builder for creating many Course entities in bulk.
type CourseCreateBulk struct {
	config
	builders []*CourseCreate
}

// Save creates the Course entities in the database.
func (ccb *CourseCreateBulk) Save(ctx context.Context) ([]*Course, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Course, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CourseCreateBulk) SaveX(ctx context.Context) []*Course {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CourseCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CourseCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
