// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kubecit-service/ent/account"
	"kubecit-service/ent/category"
	"kubecit-service/ent/course"
	"kubecit-service/ent/schema"
	"kubecit-service/ent/slider"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescOpenid is the schema descriptor for openid field.
	accountDescOpenid := accountFields[1].Descriptor()
	// account.OpenidValidator is a validator for the "openid" field. It is called by the builders before save.
	account.OpenidValidator = accountDescOpenid.Validators[0].(func(string) error)
	// accountDescPassword is the schema descriptor for password field.
	accountDescPassword := accountFields[2].Descriptor()
	// account.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	account.PasswordValidator = accountDescPassword.Validators[0].(func(string) error)
	// accountDescMethod is the schema descriptor for method field.
	accountDescMethod := accountFields[3].Descriptor()
	// account.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	account.MethodValidator = accountDescMethod.Validators[0].(func(string) error)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	courseFields := schema.Course{}.Fields()
	_ = courseFields
	// courseDescUpdatedAt is the schema descriptor for updated_at field.
	courseDescUpdatedAt := courseFields[1].Descriptor()
	// course.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	course.DefaultUpdatedAt = courseDescUpdatedAt.Default.(time.Time)
	// course.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	course.UpdateDefaultUpdatedAt = courseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// courseDescCreatedAt is the schema descriptor for created_at field.
	courseDescCreatedAt := courseFields[7].Descriptor()
	// course.DefaultCreatedAt holds the default value on creation for the created_at field.
	course.DefaultCreatedAt = courseDescCreatedAt.Default.(time.Time)
	sliderFields := schema.Slider{}.Fields()
	_ = sliderFields
	// sliderDescTitle is the schema descriptor for title field.
	sliderDescTitle := sliderFields[0].Descriptor()
	// slider.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	slider.TitleValidator = sliderDescTitle.Validators[0].(func(string) error)
	// sliderDescContent is the schema descriptor for content field.
	sliderDescContent := sliderFields[1].Descriptor()
	// slider.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	slider.ContentValidator = sliderDescContent.Validators[0].(func(string) error)
	// sliderDescImageLink is the schema descriptor for image_link field.
	sliderDescImageLink := sliderFields[2].Descriptor()
	// slider.ImageLinkValidator is a validator for the "image_link" field. It is called by the builders before save.
	slider.ImageLinkValidator = sliderDescImageLink.Validators[0].(func(string) error)
	// sliderDescCreateAt is the schema descriptor for create_at field.
	sliderDescCreateAt := sliderFields[3].Descriptor()
	// slider.DefaultCreateAt holds the default value on creation for the create_at field.
	slider.DefaultCreateAt = sliderDescCreateAt.Default.(time.Time)
	// sliderDescUpdateAt is the schema descriptor for update_at field.
	sliderDescUpdateAt := sliderFields[4].Descriptor()
	// slider.DefaultUpdateAt holds the default value on creation for the update_at field.
	slider.DefaultUpdateAt = sliderDescUpdateAt.Default.(time.Time)
	// slider.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	slider.UpdateDefaultUpdateAt = sliderDescUpdateAt.UpdateDefault.(func() time.Time)
	// sliderDescIsValid is the schema descriptor for is_valid field.
	sliderDescIsValid := sliderFields[5].Descriptor()
	// slider.DefaultIsValid holds the default value on creation for the is_valid field.
	slider.DefaultIsValid = sliderDescIsValid.Default.(bool)
}
