// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// ApplyRecord is the predicate function for applyrecord builders.
type ApplyRecord func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Chapter is the predicate function for chapter builders.
type Chapter func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Lesson is the predicate function for lesson builders.
type Lesson func(*sql.Selector)

// OrderInfos is the predicate function for orderinfos builders.
type OrderInfos func(*sql.Selector)

// Orders is the predicate function for orders builders.
type Orders func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Slider is the predicate function for slider builders.
type Slider func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VipInfo is the predicate function for vipinfo builders.
type VipInfo func(*sql.Selector)

// VipOrder is the predicate function for viporder builders.
type VipOrder func(*sql.Selector)

// VipProduct is the predicate function for vipproduct builders.
type VipProduct func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)
